--- 

  - import_tasks: f5-upload-image.yml
    tags:
      - pre-upgrade

  - import_tasks: f5-pre-upgrade-tasks.yml
    tags:
      - pre-upgrade


  # - import_tasks: f5-pre-upgrade-relicense.yml
  #   tags:
  #     - pre-upgrade-hosts
