- name: Parse the volume to get rid of the slash character
  set_fact:
    volume: "{{ volumes[0].split(\"/\")[0] }}"
  tags:
    - upgrade


- name: Debug the volume value
  debug:
    msg:  "{{ volume }}"
  tags:
    - upgrade

- name: Delete the closest inactive volume
  uri:
    url: "https://{{ inventory_hostname }}/mgmt/tm/sys/software/volume/{{ volume }}"
    user: "{{ username }}"
    password: "{{ password }}"
    method: DELETE
    validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade

- name: pause for 120 seconds
  pause:
    seconds: 120
  tags:
    - always       